### ISSUE TITLE
undefined tag 'stylesheet'|'javascript'|'asset' + undefined method `url_encode' for # after upgrading to 1.1.1

### ISSUE THREAD

**Issue by joshie** [radiant/radiant#359]
I upgraded from 1.0.1 to 1.1.1 and now my pages load these errors (and im sure others)

I suspect this is all related to the same problem but I am having trouble gathering relevant debug information
